# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wamplay.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class WAMPLayUI(object):
    def setupUi(self, WAMPlay):
        WAMPlay.setObjectName("WAMPlay")
        WAMPlay.resize(720, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WAMPlay.sizePolicy().hasHeightForWidth())
        WAMPlay.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(WAMPlay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setSizeIncrement(QtCore.QSize(1, 0))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_main = QtWidgets.QTabWidget(self.centralWidget)
        self.tab_main.setObjectName("tab_main")
        self.tab_call = QtWidgets.QWidget()
        self.tab_call.setObjectName("tab_call")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_call)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_call_topic = QtWidgets.QLineEdit(self.tab_call)
        self.line_edit_call_topic.setObjectName("line_edit_call_topic")
        self.horizontalLayout.addWidget(self.line_edit_call_topic)
        self.button_call = QtWidgets.QPushButton(self.tab_call)
        self.button_call.setObjectName("button_call")
        self.horizontalLayout.addWidget(self.button_call)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_call)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.text_edit_call_data = QtWidgets.QTextEdit(self.tab_call)
        self.text_edit_call_data.setObjectName("text_edit_call_data")
        self.verticalLayout_2.addWidget(self.text_edit_call_data)
        self.label_2 = QtWidgets.QLabel(self.tab_call)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.text_edit_call_response = QtWidgets.QPlainTextEdit(self.tab_call)
        self.text_edit_call_response.setObjectName("text_edit_call_response")
        self.verticalLayout_2.addWidget(self.text_edit_call_response)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tab_main.addTab(self.tab_call, "")
        self.tab_subscribe = QtWidgets.QWidget()
        self.tab_subscribe.setObjectName("tab_subscribe")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_subscribe)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit_subscription_topic = QtWidgets.QLineEdit(self.tab_subscribe)
        self.line_edit_subscription_topic.setObjectName("line_edit_subscription_topic")
        self.horizontalLayout_2.addWidget(self.line_edit_subscription_topic)
        self.button_subscribe = QtWidgets.QPushButton(self.tab_subscribe)
        self.button_subscribe.setObjectName("button_subscribe")
        self.horizontalLayout_2.addWidget(self.button_subscribe)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_subscribe)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.text_edit_subscription_response = QtWidgets.QPlainTextEdit(self.tab_subscribe)
        self.text_edit_subscription_response.setObjectName("text_edit_subscription_response")
        self.verticalLayout_4.addWidget(self.text_edit_subscription_response)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.tab_main.addTab(self.tab_subscribe, "")
        self.tab_publish = QtWidgets.QWidget()
        self.tab_publish.setObjectName("tab_publish")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_publish)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_edit_publish_topic = QtWidgets.QLineEdit(self.tab_publish)
        self.line_edit_publish_topic.setObjectName("line_edit_publish_topic")
        self.horizontalLayout_3.addWidget(self.line_edit_publish_topic)
        self.button_publish = QtWidgets.QPushButton(self.tab_publish)
        self.button_publish.setObjectName("button_publish")
        self.horizontalLayout_3.addWidget(self.button_publish)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_publish)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.text_edit_publish_Data = QtWidgets.QPlainTextEdit(self.tab_publish)
        self.text_edit_publish_Data.setObjectName("text_edit_publish_Data")
        self.verticalLayout_7.addWidget(self.text_edit_publish_Data)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tab_main.addTab(self.tab_publish, "")
        self.verticalLayout.addWidget(self.tab_main)
        WAMPlay.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(WAMPlay)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFie = QtWidgets.QMenu(self.menuBar)
        self.menuFie.setObjectName("menuFie")
        WAMPlay.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(WAMPlay)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtWidgets.QAction(WAMPlay)
        self.actionConnect.setObjectName("actionConnect")
        self.menuFie.addAction(self.actionConnect)
        self.menuFie.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFie.menuAction())

        self.retranslateUi(WAMPlay)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WAMPlay)

    def retranslateUi(self, WAMPlay):
        _translate = QtCore.QCoreApplication.translate
        WAMPlay.setWindowTitle(_translate("WAMPlay", "WAMPlay"))
        self.line_edit_call_topic.setPlaceholderText(_translate("WAMPlay", "WAMP Topic"))
        self.button_call.setText(_translate("WAMPlay", "Call"))
        self.label.setText(_translate("WAMPlay", "Data:"))
        self.label_2.setText(_translate("WAMPlay", "Response"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_call), _translate("WAMPlay", "Call"))
        self.line_edit_subscription_topic.setPlaceholderText(_translate("WAMPlay", "WAMP Topic"))
        self.button_subscribe.setText(_translate("WAMPlay", "Subscribe"))
        self.label_3.setText(_translate("WAMPlay", "Response:"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_subscribe), _translate("WAMPlay", "Subscribe"))
        self.line_edit_publish_topic.setPlaceholderText(_translate("WAMPlay", "WAMP Topic"))
        self.button_publish.setText(_translate("WAMPlay", "Publish"))
        self.label_4.setText(_translate("WAMPlay", "Data:"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_publish), _translate("WAMPlay", "Publish"))
        self.menuFie.setTitle(_translate("WAMPlay", "File"))
        self.actionQuit.setText(_translate("WAMPlay", "Quit"))
        self.actionConnect.setText(_translate("WAMPlay", "Connect"))

