# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wamplay.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class WAMPLayUI(object):
    def setupUi(self, WAMPlay):
        WAMPlay.setObjectName("WAMPlay")
        WAMPlay.resize(609, 439)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WAMPlay.sizePolicy().hasHeightForWidth())
        WAMPlay.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(WAMPlay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setSizeIncrement(QtCore.QSize(1, 0))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_topic = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_topic.sizePolicy().hasHeightForWidth())
        self.line_edit_topic.setSizePolicy(sizePolicy)
        self.line_edit_topic.setInputMask("")
        self.line_edit_topic.setObjectName("line_edit_topic")
        self.horizontalLayout.addWidget(self.line_edit_topic)
        self.push_button_call = QtWidgets.QPushButton(self.centralWidget)
        self.push_button_call.setObjectName("push_button_call")
        self.horizontalLayout.addWidget(self.push_button_call)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setSizeIncrement(QtCore.QSize(1, 0))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.text_edit_response = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_edit_response.sizePolicy().hasHeightForWidth())
        self.text_edit_response.setSizePolicy(sizePolicy)
        self.text_edit_response.setSizeIncrement(QtCore.QSize(1, 0))
        self.text_edit_response.setObjectName("text_edit_response")
        self.gridLayout.addWidget(self.text_edit_response, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        WAMPlay.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(WAMPlay)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 609, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFie = QtWidgets.QMenu(self.menuBar)
        self.menuFie.setObjectName("menuFie")
        WAMPlay.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(WAMPlay)
        self.statusBar.setObjectName("statusBar")
        WAMPlay.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(WAMPlay)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtWidgets.QAction(WAMPlay)
        self.actionConnect.setObjectName("actionConnect")
        self.menuFie.addAction(self.actionConnect)
        self.menuFie.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFie.menuAction())

        self.retranslateUi(WAMPlay)
        QtCore.QMetaObject.connectSlotsByName(WAMPlay)

    def retranslateUi(self, WAMPlay):
        _translate = QtCore.QCoreApplication.translate
        WAMPlay.setWindowTitle(_translate("WAMPlay", "WAMPlay"))
        self.line_edit_topic.setPlaceholderText(_translate("WAMPlay", "Topic"))
        self.push_button_call.setText(_translate("WAMPlay", "Call"))
        self.label_2.setText(_translate("WAMPlay", "Response"))
        self.label.setText(_translate("WAMPlay", "Data:"))
        self.menuFie.setTitle(_translate("WAMPlay", "File"))
        self.actionQuit.setText(_translate("WAMPlay", "Quit"))
        self.actionConnect.setText(_translate("WAMPlay", "Connect"))

